# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20170927_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='products',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
